name: Confluent Terraform

on: [ push ]

jobs:
  Terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Test Terraform
        run: terraform version
        run: echo "$CONFLUENT_CLOUD_API_KEY_ZVFS3GCRAYMYT7J5"
